jwks/internal-dev/9baed6f4-1361-4a8e-8531-1f8426e3aba8.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1581

APM-1542 Add JWK test app public key

---

jwks/int/98450897-4838-4408-bddc-dec7e9c92981.json

added jwks for WMAS

---

jwks/int/2623a326-0c9e-49a2-97cc-b2fd523d8854.json

Jira reference: APM-1611
Other notes: temporary addition of key for newly-created app for pen test purposes

Add key for pen test

---

jwks/internal-dev/e143bb5f-ce9d-4adf-b5b2-2f25ae380c66.json

APM-1622 Add asid testing app creds

---

jwks/prod/17265e91-4703-4dc8-ba0d-a4070bbc326c.json

Jira reference: APM-1590
Other notes: Temporary addition - to be removed following smoke test

APM-1590 Temporary addition of public key for PDS smoke test

---

jwks/prod/17265e91-4703-4dc8-ba0d-a4070bbc326c.json

Jira reference: APM-1590
Other notes: Removal of app following smoke test

APM-1590 Remove test app from keystore following smoke test

---

jwks/int/3167c082-fbc8-4d5c-8036-1f0c4d8af3bf.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1682
Other notes: For Oauth Pen test

APM-1682 Add key for pen test

---

jwks/int/9a625416-1fa5-4879-972b-c84083d44d4c.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APMSPII-594
Other notes:

APMSPII-594 - added public key to INT for wizitron

---

.gitignore
jwks/int/8c48d11d-b47a-4192-be14-164a2c889983.json

Jira reference: APM-1162
Other notes: Adding key to integration environment for CSL

APM-1162 Add csl jwk key

---

jwks/internal-dev/05534899-11a0-4a76-9e47-b1fd52a15ff6.json
jwks/internal-dev/278af795-6884-42dd-a713-f2b03927abb5.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/AEA-915
Other notes:

AEA-915: Example JWKS for Signing Service sandbox & smoke tests

---

jwks/int/462fb1dc-e361-4b7e-bdd4-5b4c9e02054b.json

Jira reference: apmspii-628
Other notes:

apmspii-628 add key for app 462fb1dc-e361-4b7e-bdd4-5b4c9e02054b

---

jwks/prod/d99a2666-4d9a-40e1-b4fc-0f5e7b67c6ce.json

AMB-452 Added Yorkshire Ambulance Service Prod public key

---

jwks/int/4b7fca9e-a23b-4218-ad82-fd241307af18.json

Jira reference: APMSPII-654
Other notes:

APMSPII-654 Public key for "Find-my-NHS-number" Int environment

---

jwks/internal-dev/766dc849-3f4a-454e-b26e-be8949e93f5f.json

Jira reference: APM-1701 Identity Service- Analyze and Prevent 'Wrong Product' Bug 
Other notes:
Key to be used with APM-1701 Testing app.

APM-1701 Key for app and testing ticket

---

jwks/internal-dev/d574ab27-014e-48ea-b8f3-25bad2aa1c46.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/AEA-1023
Other notes:

Add signing-service internal-dev testing JWKS

---

jwks/int/4960638b-c9ab-44e2-b3ca-1a7d0a56d49b.json
jwks/int/7f87da69-8f66-43e0-81ae-fe5e28b69779.json
jwks/int/a4a26a17-27b2-4ca7-8ef2-454a8b327dc.json
jwks/prod/5e63f558-98ef-4fa6-8644-8a186561303b.json

Jira reference: APMSPII-670
Other notes:

APMSPII-670: Keys for NIVS applications (Int and Prod)

---

jwks/internal-dev/id-token-jwks.json
jwks/internal-dev/id-token-nhsid-identity-service-tests-jwks.json

jwks for mock NHS ID id tokens

---

jwks/int/0fd0c37f-a81f-4b9c-a6c0-896a1dff76dd.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1813
Other notes:

APM-1813 Add Elisian jwks for int

---

jwks/int/0fd0c37f-a81f-4b9c-a6c0-896a1dff76dd.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1813
Other notes:

APM-1813 Add linuxtest-1 jwk to app

---

jwks/int/c7bb1bc1-0d0d-43b5-b799-93d87a95a0ae.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1830
Other notes:

APM-1830 Add jwks for supplychain

---

jwks/int/66dcbab9-63a3-4ac5-9c2b-9c0cfe4c8720.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1833
Other notes:

APM-1833 Add jwks endpoint

---

jwks/internal-dev/66dcbab9-63a3-4ac5-9c2b-9c0cfe4c8720.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1833
Other notes:

APM-1833 Add second key for paul

---

jwks/internal-dev/245de17b-e780-46bf-b30b-6742b9ee5713.json

Jira reference: APM-1847
Other notes:

APM-1847 Paul Sharpe key setup

---

jwks/int/1c9c85c9-d3d2-47af-8729-36ebc4ee4aca.json

Jira reference: APM-1853 
Other notes: Key for int environment

APM-1853 Paul Sharpe key for int (1c9c85c9-d3d2-47af-8729-36ebc4ee4aca)

---

jwks/int/f1e2120b-72ff-4327-9a4b-e71507f80d52.json

Jira reference: APM-1859
Other notes: Meddbase - KKusnadi - wants a public key registered

APM-1813 Add Key for App ID: f1e2120b-72ff-4327-9a4b-e71507f80d52

---

jwks/int/e1dca037-94f6-4d6a-9bd4-a12be4706bf6.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1872
Other notes: Single key added. First time following the KOP, please be gentle!

Add key for Iain Pretty

---

jwks/int/2f80932a-2b3e-4fa3-a424-5d77e917ce82.json
scripts/make_jwk.py

Jira reference: APM-1906
- Now handles insertion into required file.
- Checks if keys already exist.

APM-1906 add jwks entry for 2f80932a-2b3e-4fa3-a424-5d77e917ce82

---

jwks/int/808f7d87-1497-47f0-8f48-5c8a72851682.json

-------
Jira reference: APM-1911
Other notes:

APM-1911 Add alldayDr Healthya app key for int

---

jwks/int/afa99896-7e9b-4c1f-9d6f-1120b9df84ee.json

Jira reference: APMSPII-796
Other notes:

APMSPII-796: Int key for Covid community testing

---

jwks/int/c54b4302-12eb-49a5-a3f7-30fb1dca9513.json
scripts/make_jwk.py

Jira reference: APM-1912
Other notes:
* Updated make_jwks.py to fix a bug with empty files

Apm 1912 alphalake jwks

---

jwks/int/b384210e-ec66-4e6c-b51c-3f1814719ae4.json

Jira reference: APM-1920
Other notes:

APM-1920 Add Alphalake public key to int environment

---

jwks/int/6e758845-c73f-48ab-a5df-2d300ff1673e.json

Jira reference:  APMSPII-815
Other notes:

APMSPII-815 add jwks entry for 6e758845-c73f-48ab-a5df-2d300ff1673e

---

jwks/int/10f0bc34-f8e3-41b2-9850-d30741b825f3.json

New User restricted application AT01

---

jwks/int/afa99896-7e9b-4c1f-9d6f-1120b9df84ee.json

Jira reference: APM-1956
Other notes:

APM-1956 Add test and trace public key

---

jwks/int/9a444d60-746d-4337-b055-a3990bae01c6.json

-------
Jira reference: APM-1924

APM-1924 Add JWKS for Evolutio Software

---

jwks/int/879725dc-3fac-42e1-83ae-7cc997ddaf10.json

APM-1963 Add allscripts jwks to int env

---

jwks/int/9dd22daa-b874-42e6-8f9f-42f845483e82.json

APM-1965 Add 111 JWKS endpoint

---

jwks/internal-dev/f7fbd857-7aed-4270-a667-84a21a46b4f1.json

Add new jwks for paz internal-dev spike pds test.

---

jwks/int/10f0bc34-f8e3-41b2-9850-d30741b825f3.json

Created new jwks file for testing purposes

---

jwks/int/ed9961e6-886f-4875-bda2-34a90138abfc.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1984
Other notes: Netcompany

APM-1162 Add key for ed9961e6-886f-4875-bda2-34a90138abfc

---

jwks/int/0331f48c-a9bc-49e9-a27b-c131d1d5966e.json

Jira reference:  [APM-1997](https://nhsd-jira.digital.nhs.uk/browse/APM-1997)
Other notes:

APM-1997 iPlato public key

---

jwks/int/939948c9-e449-4baa-8bc4-497fbbe4d914.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-1998
Other notes:

APM-1998 Add jwks for imm hist pen test

---

jwks/int/2c51653e-692b-4fac-bfc7-6b00fd4e46c6.json

Jira reference: 
https://nhsd-jira.digital.nhs.uk/browse/AEA-1294
Other notes:
required for setting up a test app for the signing service in int
sorry about branch name - ticket is AEA-1294

add jwk for signing service int test app

---

jwks/int/8e07461f-056a-493d-a9cc-0816c5c5ac8c.json

-------
Jira reference: [APM-2030](https://nhsd-jira.digital.nhs.uk/browse/APM-2030)

APM-2030 Add BESA-Test

---

jwks/int/773d0385-eb68-42ee-ac04-3dbee4e5cc2e.json

-------
Jira reference: [APM-2028](https://nhsd-jira.digital.nhs.uk/browse/APM-2028)

APM-2028 Add Integration - Application-Restricted Access

---

jwks/int/88dfcc0a-52a7-455a-88b5-dc3159002f3e.json

-------
Jira reference: [APM-2026](https://nhsd-jira.digital.nhs.uk/browse/APM-2026)

APM-2026 Add PAS-DEV

---

jwks/prod/c8043291-c885-4817-84d4-7699d270be9d.json

-------
Jira reference: [APM-2027](https://nhsd-jira.digital.nhs.uk/browse/APM-2027)

APM-2027 Add Evacc - PROD

---

jwks/int/07cd0159-4b4c-4023-9c5a-45de98913da0.json

-------
Jira reference: [AMB-605](https://nhsd-jira.digital.nhs.uk/browse/AMB-605)

AMB-605 Add key for test gurdeep test app

---

jwks/int/07cd0159-4b4c-4023-9c5a-45de98913da0.json

Hopefully the release pipeline will work this time...
-------
Jira reference: [AMB-605](https://nhsd-jira.digital.nhs.uk/browse/AMB-605)

AMB-605 (Re) add key for Gurdeep's test app

---

jwks/int/a7e03ceb-2570-42e6-a7c9-624ea15269c8.json

-------
Jira reference: [APM-2035](https://nhsd-jira.digital.nhs.uk/browse/APM-2035)

APM-2035 Add key for Check your coronavirus vaccine record INT

---

jwks/sandbox/89539c3d-87ee-4cd1-819a-f04a07cfcbfe.json
scripts/make_jwk.py

-------
Jira reference: [APM-2042](https://nhsd-jira.digital.nhs.uk/browse/APM-2042)

APM-2042 Add key for BEST_TEST_INT

---

jwks/int/3f03d4c5-1702-4f3a-8ffb-9c060a566669.json
jwks/int/c3c448a8-1473-4958-a001-f0e65bec70b3.json

-------
Jira reference: [APM-2046](https://nhsd-jira.digital.nhs.uk/browse/APM-2046)

APM-2046 add keys for allscripts

---

jwks/prod/2940830f-243c-4bd9-bb7c-306130cce541.json

Jira reference: APM-2056
Other notes:
https://nhsd-jira.digital.nhs.uk/browse/APM-2056

APM-2056 Add netcompany prod jwks

---

jwks/int/831e170e-fb96-4f63-9267-f21324a432ef.json

Jira reference: APM-2057
Other notes:

APM-2057 Add medicus int jwks

---

jwks/int/595fa60a-145a-48aa-beff-d3c333da3181.json

Recreating app to move it over to developer team.

APM-1162 Move Eva Health Int app to new app id

---

jwks/int/5fcba1f7-8664-4c2d-8d91-c4ee34f3452d.json

Jira reference: APM-2059
Other notes:

APM-2059 Add dotsquare int jwks

---

jwks/int/07d61204-55d1-4ed5-bf1d-9dcf65f776aa.json

Jira reference: APM-2062
Other notes:

APM-2062 Add manchester uni jwks key

---

jwks/int/5fcba1f7-8664-4c2d-8d91-c4ee34f3452d.json

Jira reference: APM-2063
Other notes:

APM-2063 Add dotsquared revised public key

---

jwks/int/5fcba1f7-8664-4c2d-8d91-c4ee34f3452d.json

Jira reference: APM-2063
Other notes:
* Update due to same kid as other public key

APM-2063 Update docsquared jwks kid

---

scripts/make_jwk.py

* make_jwt.py alteration
* Check for existing kid
Jira reference: APM-2017

APM-2017 Add check for duplicate use of kid

---

jwks/prod/d584486e-5db4-4c11-a27a-f5b157a06582.json

Added NWAS Prod public key

---

jwks/ref/b6f8a777-dc16-4d9b-82ed-00a91f0f9c36.json

mm: replicate nc public key for ref

---

jwks/int/b5b4549e-6f1a-4e7a-b69c-69f49ebac72b.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-2121
Other notes: This is a manual push because the jwks-helper is returning a 500 for this key. 

APM-2121-Integration-env-Nurturey-app

---

jwks/int/66a83a27-ce6d-49d0-b44a-f835ba4e89cb.json

APM-2209 Replace north of england commissioning key

---

jwks/int/72441c5f-2bd2-46a6-a6e9-41e527ffc6fe.json

APM-2016 Remove whitespace

---

jwks/internal-dev/9baed6f4-1361-4a8e-8531-1f8426e3aba8.json

AMB-847 duplicated key and changed kid for rs512

---

jwks/prod/bc2b2fcf-ca1a-4128-9262-aaa93ec12c7f.json

Reverts NHSDigital/identity-service-jwks#232

Revert "Revert "JWKS request for East Midlands Medical Service""

---

azure/components/deploy-jwks-env.yml

APM-2016 Comment out caching

---

azure/components/deploy-jwks-env.yml

APM-2016 Add caching back in

---

jwks/internal-dev/2612f6b9-e935-4ebd-b187-fb3fbe6b7169.json

add new key pair with id test-1
Jira reference: https://nhsd-jira.digital.nhs.uk/browse/AEA-1917
Other notes:

aea-1917-update-users-to-match

---

jwks/int/2905e158-41e5-4293-84ae-b2e475125f21.json

AMB-1032 East Midlands Ambulance INT JWKS manual add

---

jwks/internal-dev/id-token-proxygen-tests-jwks.json

APM-2982 Add key to internal-dev for proxygen

---

jwks/int/02dfd3b0-8423-487e-81ab-3e845c0fd4fa.json

Reverts NHSDigital/identity-service-jwks#405

Revert "JWKS request for NHSD"

---

jwks/internal-dev/proxygen-tardis-machine-user-jwks.json

Jira reference: APM-3269
Other notes:

JWKS request for Tardis

---

jwks/paas/hello-world.json
jwks/paas/id-token-proxygen-tests-jwks.json
jwks/paas/proxygen-tardis-machine-user-jwks.json
scripts/make_jwk.py
scripts/poetry.lock

APM-3001 Add hello the jwks

---

jwks/int/2ec9528e-4853-41d2-9ae9-b784c4ee5d56.json

APM-1832 Add second app

---

jwks/prod/ad93cd9c-b48f-4921-8d13-f3978f4a354d.json

APM-3784: added new key for nhs app

---

jwks/prod/ad93cd9c-b48f-4921-8d13-f3978f4a354d.json

APM-3784B: removed old key

---

jwks/paas/gp-registrations-management-information.json

-------
Jira reference: APM-3954
Other notes:

APM-3954 gp-registrations-management-information paas client JWKS

---

jwks/int/ada4bfda-05b3-4a22-b323-ab36bb32c2b7.json

Jira reference: https://nhsd-jira.digital.nhs.uk/browse/APM-4033
Other notes: Add algorithm value of RS512 to jwks endpoint.

APM-4033: Add 'alg' value to jwks endpoint

---

jwks/paas/structured-scr.json

Apm-4421 structured scr creation

---

jwks/paas/structured-scr.json

APM-4421. Amdended the key id.

---

jwks/paas/pipeline-cleanup.json

APM-3424 Add pipeline paas client

---

jwks/paas/proxygen-api-specification.json

APM-3423. Added the proxygen-api-specification JWKS.

---

jwks/prod/dbabe489-5e71-4040-9b31-72b797a151a3.json

APM-4153 Adjust kid for dbabe489-5e71-4040-9b31-72b797a151a3

---

jwks/paas/alexc-proxygen-client.json

APM-0000 Add AC testing jwks for paas

---

jwks/paas/alexh-test-api.json

APM-4430: JWKS for alexh-test-api paas development API

---

jwks/paas/nhs-website-content-api.json

APM-0000. Added Proxygen key for NHS Website Content API team

---

jwks/prod/776f402a-2ba8-4199-9c87-3cffc5972151.json

APM-4736. JWKS for Prod app enablement.

---

jwks/paas/fgm-flag.json

Jira reference: N/A
Other notes: 
request from APIM producer support
https://nhsdigital-platforms.slack.com/archives/C016JRWN6AY/p1697450402394199

JWKS request for fgm-flag

---

jwks/paas/ra-flag.json

APM-0000 Create jwks for ra-flag

---

jwks/prod/96cad8ba-1420-468f-b53a-13d80cc4bd4a.json

APM-4873. Added Spine-MNS-Prod JWKS file to identity service.

---

jwks/paas/connecting-party-manager.json

APM-0000: Connecting party manager proxygen

---

jwks/paas/digital-staff-passport-api-standard.json

Add key for digital staff passport api standard

---

jwks/prod/0097886b-02ea-4324-a78d-692dc38ec2e7.json

APM-5145. Enable CLEO Systems 24 PDS FHIR Prod app

---

jwks/prod/9c6c9118-f111-4b5c-8a9f-27e9f82f6986.json

APM-5169. Added UKHSA PDS app JWKS file.

---

jwks/paas/prescription-status-update-api.json

APM-0000: Add prescription-status-update-api jwks for proxygen

---

jwks/paas/vn-test.json

Proxygen Setup

---

jwks/prod/c3e0ff83-6875-4ffc-ac61-ed08f6805f8e.json

The change in the KID

---

jwks/paas/nhse-tsas-solarch-mhds-registry.json

https://nhsdigital-platforms.slack.com/archives/C016JRWN6AY/p1715074292396609
Other notes:

APM-0000 Public key for Proxygen API nhse-tsas-solarch-mhds-registry

---

jwks/paas/genomic-order-management-service.json

APM-0000 Add genomic-order-management-service proxygen key

---

jwks/paas/register-with-a-gp-surgery.json

APM-0000: Create proxygen jwks for register-with-a-gp-surgery

---

jwks/paas/custom-prescription-status-update-api.json

custom-prescription-status-update-api Proxygen Keycloack

---

jwks/paas/sigma-test.json

sigma-test

---

jwks/paas/patient-audit-record-service-api.json

Proxygen public key for patient-audit-record-service-api

---

jwks/paas/sophiec-test-api.json

Proxygen public key for sc test api

---

jwks/paas/patient-data-manager.json

APM-0000: Create patient data manager jwks

---

jwks/paas/cpis-unscheduled-care-event-api.json

cpis-unscheduled-care-Jwks

---

jwks/paas/hello-world-api-docker-test.json

Creating the Hello-world-api for go-register team issue fixing

---

jwks/paas/prescription-clinical-tracker.json

prescription-clinical-tracker proxygen jwks

---

jwks/paas/dwa-middle-service-api.json

APM-0000: Create proxygen api for dwa-middle-service-api

---

jwks/paas/clinical-prescription-tracker.json

clinical-prescription-tracker-jwks

---

jwks/paas/healthcare-worker-api.json

jwks-healthcare-worker-api

---

jwks/paas/FHIR-dispensing.json

JWKS request for FHIR-dispensing.json

---

jwks/paas/fhir-prescribing.json

updated JWKS file
Other notes:

JWKS request for fhir-prescribing

---

jwks/paas/fhir-dispensing.json

jwks-request-for-fhir-dispensing

---

jwks/paas/mns-mock-hydration-1.json

APM-0000: Create proxygen jwks for mns-mock-hydration

---

jwks/prod/a0655517-2bd7-4e16-98d0-c6a0f2b97ed0.json

Change in a0655517-2bd7-4e16-98d0-c6a0f2b97ed0

---

jwks/paas/national-document-repository.json

national-document-repository

---

jwks/prod/c689d9f0-4b2e-440d-9a34-3c8ffa8860d5.json

DrDoctor-NotificationsMessaging-Production

---

jwks/prod/3c50cc3d-1c16-4c98-8ddb-84e1987c42ad.json

Optegra - Compucare 8 Final

---

jwks/prod/ffa2bdd7-e46a-453b-afa1-9001a6a9812c.json

Cinapsis kid change

---

jwks/paas/sri-migration-api.json

APM-0000 Add Sri Migration API key

---

jwks/paas/nir-retrieval-proxy-poc.json

New proxygen API request -> https://nhsdigital-platforms.slack.com/archives/C016JRWN6AY/p1736846769791429

APM-0000 Add nir-retrieval-proxy-poc proxygen key

---

jwks/paas/test-results.json

test-results api

---

jwks/paas/uec-eps-dos.json

uec-eps-dos jwks

---

jwks/paas/new-api.json

jwks registration for proxygen test-amit

---

jwks/paas/rishi-proxygen.json

Added public key for proxygen test

---

jwks/paas/test-api-vini.json

test proxygen

---

jwks/paas/uec-dos.json

JWKS-request-for-UED-DOS

---

jwks/paas/uec-dos-ingestion-api.json

JWKS-request-for-UEC-DOS-INGESTION

---

jwks/paas/digital-genomics-test-directory-service.json

digital-Genomics

---

jwks/paas/pentest-proxygen-rbac.json

second pentest jwks for proxygen

---

jwks/paas/ftrs-search.json

Reverts NHSDigital/identity-service-jwks#941

Revert "Revert "ftrs-search api changes""

---

jwks/paas/uec-dos-soap.json

SCTASK0280465 uec-dos-soap

---

jwks/prod/6b91b925-9dce-40e4-b721-dbff86949ac2.json

Add new Key for Compucare 8 - SCTASK0282063

---

jwks/int/c24e6128-e4dc-4924-9543-7909f5c04aec.json

Append new JWKS for NECS (non-prod INT)-SCTASK0287701

---

jwks/paas/triage-api.json

triage-api

---

jwks/paas/raghu-test-api.json

NA
Other notes:
Added Raghu-Test-API JWKS file

Added JWKS Test file
